# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'turn_assignment.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TurnAssignment(object):
    def setupUi(self, TurnAssignment):
        TurnAssignment.setObjectName("TurnAssignment")
        TurnAssignment.resize(714, 519)
        self.centralwidget = QtWidgets.QWidget(TurnAssignment)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(5, 30, 691, 471))
        self.tabs.setObjectName("tabs")
        self.tabConfig = QtWidgets.QWidget()
        self.tabConfig.setObjectName("tabConfig")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabConfig)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.cbbStudents = QtWidgets.QComboBox(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.cbbStudents.setFont(font)
        self.cbbStudents.setObjectName("cbbStudents")
        self.cbbStudents.addItem("")
        self.cbbStudents.addItem("")
        self.cbbStudents.addItem("")
        self.cbbStudents.addItem("")
        self.horizontalLayout_4.addWidget(self.cbbStudents)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.tabConfig)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.cbbYear = QtWidgets.QComboBox(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.cbbYear.setFont(font)
        self.cbbYear.setObjectName("cbbYear")
        self.cbbYear.addItem("")
        self.cbbYear.addItem("")
        self.cbbYear.addItem("")
        self.cbbYear.addItem("")
        self.cbbYear.addItem("")
        self.horizontalLayout_4.addWidget(self.cbbYear)
        self.label_2 = QtWidgets.QLabel(self.tabConfig)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.cbbMonth = QtWidgets.QComboBox(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.cbbMonth.setFont(font)
        self.cbbMonth.setObjectName("cbbMonth")
        self.cbbMonth.addItem("")
        self.cbbMonth.addItem("")
        self.cbbMonth.addItem("")
        self.cbbMonth.addItem("")
        self.cbbMonth.addItem("")
        self.cbbMonth.addItem("")
        self.cbbMonth.addItem("")
        self.cbbMonth.addItem("")
        self.cbbMonth.addItem("")
        self.cbbMonth.addItem("")
        self.cbbMonth.addItem("")
        self.cbbMonth.addItem("")
        self.horizontalLayout_4.addWidget(self.cbbMonth)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.lbDate = QtWidgets.QLabel(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbDate.setFont(font)
        self.lbDate.setObjectName("lbDate")
        self.verticalLayout_3.addWidget(self.lbDate)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btnClean = QtWidgets.QPushButton(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnClean.setFont(font)
        self.btnClean.setObjectName("btnClean")
        self.horizontalLayout_3.addWidget(self.btnClean)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnSubmit = QtWidgets.QPushButton(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setObjectName("btnSubmit")
        self.horizontalLayout_3.addWidget(self.btnSubmit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbMon = QtWidgets.QCheckBox(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.cbMon.setFont(font)
        self.cbMon.setObjectName("cbMon")
        self.horizontalLayout.addWidget(self.cbMon)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.cbTus = QtWidgets.QCheckBox(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.cbTus.setFont(font)
        self.cbTus.setObjectName("cbTus")
        self.horizontalLayout.addWidget(self.cbTus)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.cbWed = QtWidgets.QCheckBox(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.cbWed.setFont(font)
        self.cbWed.setObjectName("cbWed")
        self.horizontalLayout.addWidget(self.cbWed)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.cbThu = QtWidgets.QCheckBox(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.cbThu.setFont(font)
        self.cbThu.setObjectName("cbThu")
        self.horizontalLayout.addWidget(self.cbThu)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbFri = QtWidgets.QCheckBox(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.cbFri.setFont(font)
        self.cbFri.setObjectName("cbFri")
        self.horizontalLayout_2.addWidget(self.cbFri)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.cbSat = QtWidgets.QCheckBox(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.cbSat.setFont(font)
        self.cbSat.setObjectName("cbSat")
        self.horizontalLayout_2.addWidget(self.cbSat)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.cbSun = QtWidgets.QCheckBox(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.cbSun.setFont(font)
        self.cbSun.setObjectName("cbSun")
        self.horizontalLayout_2.addWidget(self.cbSun)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.calendar = QtWidgets.QCalendarWidget(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.calendar.setFont(font)
        self.calendar.setObjectName("calendar")
        self.verticalLayout_2.addWidget(self.calendar)
        self.label_4 = QtWidgets.QLabel(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.lbWeekday = QtWidgets.QLabel(self.tabConfig)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbWeekday.setFont(font)
        self.lbWeekday.setObjectName("lbWeekday")
        self.gridLayout.addWidget(self.lbWeekday, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabs.addTab(self.tabConfig, "")
        self.tabShow = QtWidgets.QWidget()
        self.tabShow.setObjectName("tabShow")
        self.tableInfo = QtWidgets.QTableWidget(self.tabShow)
        self.tableInfo.setGeometry(QtCore.QRect(0, 0, 671, 461))
        self.tableInfo.setObjectName("tableInfo")
        self.tableInfo.setColumnCount(7)
        self.tableInfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(6, item)
        self.tabs.addTab(self.tabShow, "")
        self.tabTable = QtWidgets.QWidget()
        self.tabTable.setObjectName("tabTable")
        self.tableTurn = QtWidgets.QTableWidget(self.tabTable)
        self.tableTurn.setGeometry(QtCore.QRect(0, 11, 691, 441))
        self.tableTurn.setObjectName("tableTurn")
        self.tableTurn.setColumnCount(7)
        self.tableTurn.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTurn.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTurn.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTurn.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTurn.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTurn.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTurn.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTurn.setHorizontalHeaderItem(6, item)
        self.tabs.addTab(self.tabTable, "")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 671, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnConfig = QtWidgets.QPushButton(self.layoutWidget)
        self.btnConfig.setObjectName("btnConfig")
        self.horizontalLayout_5.addWidget(self.btnConfig)
        self.btnView = QtWidgets.QPushButton(self.layoutWidget)
        self.btnView.setObjectName("btnView")
        self.horizontalLayout_5.addWidget(self.btnView)
        self.btnSave = QtWidgets.QPushButton(self.layoutWidget)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_5.addWidget(self.btnSave)
        self.btnGen = QtWidgets.QPushButton(self.layoutWidget)
        self.btnGen.setObjectName("btnGen")
        self.horizontalLayout_5.addWidget(self.btnGen)
        self.btnExport = QtWidgets.QPushButton(self.layoutWidget)
        self.btnExport.setObjectName("btnExport")
        self.horizontalLayout_5.addWidget(self.btnExport)
        TurnAssignment.setCentralWidget(self.centralwidget)
        self.label.setBuddy(self.cbbStudents)

        self.retranslateUi(TurnAssignment)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TurnAssignment)

    def retranslateUi(self, TurnAssignment):
        _translate = QtCore.QCoreApplication.translate
        TurnAssignment.setWindowTitle(_translate("TurnAssignment", "值日表生成器"))
        self.label.setText(_translate("TurnAssignment", "学生姓名"))
        self.cbbStudents.setItemText(0, _translate("TurnAssignment", "赵浩宇"))
        self.cbbStudents.setItemText(1, _translate("TurnAssignment", "李婧语"))
        self.cbbStudents.setItemText(2, _translate("TurnAssignment", "李佳凝"))
        self.cbbStudents.setItemText(3, _translate("TurnAssignment", "陈婧媱"))
        self.label_5.setText(_translate("TurnAssignment", "值日年份"))
        self.cbbYear.setItemText(0, _translate("TurnAssignment", "2016"))
        self.cbbYear.setItemText(1, _translate("TurnAssignment", "2017"))
        self.cbbYear.setItemText(2, _translate("TurnAssignment", "2018"))
        self.cbbYear.setItemText(3, _translate("TurnAssignment", "2019"))
        self.cbbYear.setItemText(4, _translate("TurnAssignment", "2020"))
        self.label_2.setText(_translate("TurnAssignment", "值日月份"))
        self.cbbMonth.setItemText(0, _translate("TurnAssignment", "1"))
        self.cbbMonth.setItemText(1, _translate("TurnAssignment", "2"))
        self.cbbMonth.setItemText(2, _translate("TurnAssignment", "3"))
        self.cbbMonth.setItemText(3, _translate("TurnAssignment", "4"))
        self.cbbMonth.setItemText(4, _translate("TurnAssignment", "5"))
        self.cbbMonth.setItemText(5, _translate("TurnAssignment", "6"))
        self.cbbMonth.setItemText(6, _translate("TurnAssignment", "7"))
        self.cbbMonth.setItemText(7, _translate("TurnAssignment", "8"))
        self.cbbMonth.setItemText(8, _translate("TurnAssignment", "9"))
        self.cbbMonth.setItemText(9, _translate("TurnAssignment", "10"))
        self.cbbMonth.setItemText(10, _translate("TurnAssignment", "11"))
        self.cbbMonth.setItemText(11, _translate("TurnAssignment", "12"))
        self.lbDate.setText(_translate("TurnAssignment", "期望值日的日期："))
        self.btnClean.setText(_translate("TurnAssignment", "清除输入"))
        self.btnSubmit.setText(_translate("TurnAssignment", "确   定"))
        self.cbMon.setText(_translate("TurnAssignment", "星期一"))
        self.cbTus.setText(_translate("TurnAssignment", "星期二"))
        self.cbWed.setText(_translate("TurnAssignment", "星期三"))
        self.cbThu.setText(_translate("TurnAssignment", "星期四"))
        self.cbFri.setText(_translate("TurnAssignment", "星期五"))
        self.cbSat.setText(_translate("TurnAssignment", "星期六"))
        self.cbSun.setText(_translate("TurnAssignment", "星期日"))
        self.lbWeekday.setText(_translate("TurnAssignment", "期望值日的工作日："))
        self.tabs.setTabText(self.tabs.indexOf(self.tabConfig), _translate("TurnAssignment", "Tab 1"))
        item = self.tableInfo.horizontalHeaderItem(0)
        item.setText(_translate("TurnAssignment", "姓名"))
        item = self.tableInfo.horizontalHeaderItem(1)
        item.setText(_translate("TurnAssignment", "星期一"))
        item = self.tableInfo.horizontalHeaderItem(2)
        item.setText(_translate("TurnAssignment", "星期二"))
        item = self.tableInfo.horizontalHeaderItem(3)
        item.setText(_translate("TurnAssignment", "星期三"))
        item = self.tableInfo.horizontalHeaderItem(4)
        item.setText(_translate("TurnAssignment", "星期四"))
        item = self.tableInfo.horizontalHeaderItem(5)
        item.setText(_translate("TurnAssignment", "星期五"))
        item = self.tableInfo.horizontalHeaderItem(6)
        item.setText(_translate("TurnAssignment", "具体日期"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabShow), _translate("TurnAssignment", "Tab 2"))
        item = self.tableTurn.horizontalHeaderItem(0)
        item.setText(_translate("TurnAssignment", "SUN"))
        item = self.tableTurn.horizontalHeaderItem(1)
        item.setText(_translate("TurnAssignment", "MON"))
        item = self.tableTurn.horizontalHeaderItem(2)
        item.setText(_translate("TurnAssignment", "TUE"))
        item = self.tableTurn.horizontalHeaderItem(3)
        item.setText(_translate("TurnAssignment", "WED"))
        item = self.tableTurn.horizontalHeaderItem(4)
        item.setText(_translate("TurnAssignment", "THU"))
        item = self.tableTurn.horizontalHeaderItem(5)
        item.setText(_translate("TurnAssignment", "FRI"))
        item = self.tableTurn.horizontalHeaderItem(6)
        item.setText(_translate("TurnAssignment", "SAT"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabTable), _translate("TurnAssignment", "页"))
        self.btnConfig.setToolTip(_translate("TurnAssignment", "配置或者编辑个人信息"))
        self.btnConfig.setStatusTip(_translate("TurnAssignment", "配置或者编辑个人信息"))
        self.btnConfig.setWhatsThis(_translate("TurnAssignment", "配置或者编辑个人信息"))
        self.btnConfig.setText(_translate("TurnAssignment", "配置"))
        self.btnView.setToolTip(_translate("TurnAssignment", "点击查看所有已经配置的信息"))
        self.btnView.setStatusTip(_translate("TurnAssignment", "点击查看所有已经配置的信息"))
        self.btnView.setWhatsThis(_translate("TurnAssignment", "点击查看所有已经配置的信息"))
        self.btnView.setText(_translate("TurnAssignment", "查看"))
        self.btnSave.setText(_translate("TurnAssignment", "保存"))
        self.btnGen.setToolTip(_translate("TurnAssignment", "点击生成并打开值日表"))
        self.btnGen.setStatusTip(_translate("TurnAssignment", "点击生成并打开值日表"))
        self.btnGen.setWhatsThis(_translate("TurnAssignment", "点击生成并打开值日表"))
        self.btnGen.setText(_translate("TurnAssignment", "生成值日表"))
        self.btnExport.setText(_translate("TurnAssignment", "导出值日表"))

